permalink: /:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed
# 作者信息
author:
  name: KOKO
  email: 1903599011@qq.com
  link: http://gezeliheid-koko.github.io
  github: http://github.com/Gezeliheid-KOKO

# 站点信息
title: Hello~This is KOKO!
description: Welcome to explore the mysteries of the WEB!
url: https://gezeliheid.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/蜡笔小新.jpg
favicon: /assets/蜡笔小新.jpg
logo: /assets/蜡笔小新.jpg
# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/


# 定义你的分类
categories: Tech

# 排除文件夹
exclude: [robot,util,config,tutorials,main.go,install.sh,jekyll.sh,Gemfile,Gemfile.lock,jekyll_run.sh, codebase,go.mod,go.sum,util]

# 谷歌统计ID
ga_id: UA-129013660-6

# google adsense ID
gad_id: pub-6269173703140859

social:
  name: KOKO
  links:
  - https://github.com/Gezeliheid-KOKO


