on:
  issues:
    types: [opened, edited, reopened]
  schedule:
  - cron: "* */2 * * *"  
  
name: Bot
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SpiderHN
        run: go run main.go spider
      
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v1
        with:
          # The committer's email address
          email: ActionBot@mojotv.cn # default is ${{ github.actor }}@localhost
          # The committer's name
          name: ActionBotOfMojo # default is ${{ github.actor }}
          # The commit message
          message: # default is Automatically updated using GitHub Actions
          # The branch to push the changes back to, defaults to the current branch
          branch: # default is ${{ github.ref }}
          # The files to add separated by space, defaults to every file
          files: # default is .
          # The repository to push the code to, defaults to origin (e.g. this repository)
          repository: # default is origin
          # The token used to push the code, not needed if you push to the same repository
          token: # default is ${{ github.token }}
  

