on:
  issues:
    types: [opened, edited, reopened]
  schedule:
  - cron: "* */2 * * *"  
  
name: Bot
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SpiderHN
        run: go run main.go spider
      - name: show files
        run: ls -al _posts/hacknews  
      
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.6
        with:
          # Github Token with commit access
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          # Override branch to push to
          push-branch: # optional
          # Specify commit message
          commit-message: # optional, default is autocommit
          # Force add files, useful for adding ignored files.
          force-add: # optional, default is false
          # Pull and rebase before commiting. Useful when using commit inside matrix.
          rebase: # optional, default is false
          # Specific files to add.
          files: . # optional, default is 
          # Committer email. Default is ${name}@users.noreply.github.com
          email: neochau@gmail.com # optional, default is 
          # Committer name. Default is name of the person or app that initiated the workflow.
          name: ActionBot # optional, default is 
  

